### ISSUE TITLE
httpx.ConnectError: All connection attempts failed

### ISSUE THREAD

**Issue by leonardozilli** [JoshuaC215/agent-service-toolkit#108]
I reproduced the steps from [github.com/JoshuaC215/agent-service-toolkit?tab=readme-ov-file#quickstart](https://github.com/JoshuaC215/agent-service-toolkit?tab=readme-ov-file#quickstart):

Run directly in python

```sh
# At least one LLM API key is required
echo 'OPENAI_API_KEY=your_openai_api_key' >> .env

# uv is recommended but "pip install ." also works
pip install uv
uv sync --frozen
# "uv sync" creates .venv automatically
source .venv/bin/activate
python src/run_service.py

# In another shell
source .venv/bin/activate
streamlit run src/streamlit_app.py
```

The only thing I've changed are the HOST and PORT to "localhost" and "8080" respectively in `settings.py`.
Both service and streamlit app start, but I get the following error when querying the app from the browser:

```text
2024-11-30 21:31:38.149 Uncaught app exception
Traceback (most recent call last):
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 377, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    with map_exceptions(exc_map):
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/.asdf/installs/python/3.12.6/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "/home/leo/Desktop/agent-service-toolkit/src/streamlit_app.py", line 340, in <module>
    asyncio.run(main())
  File "/home/leo/.asdf/installs/python/3.12.6/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/leo/.asdf/installs/python/3.12.6/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/.asdf/installs/python/3.12.6/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/leo/Desktop/agent-service-toolkit/src/streamlit_app.py", line 154, in main
    await draw_messages(stream, is_new=True)
  File "/home/leo/Desktop/agent-service-toolkit/src/streamlit_app.py", line 202, in draw_messages
    while msg := await anext(messages_agen, None):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/Desktop/agent-service-toolkit/src/client/client.py", line 192, in astream
    async with client.stream(
               ^^^^^^^^^^^^^^
  File "/home/leo/.asdf/installs/python/3.12.6/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1628, in stream
    response = await self.send(
               ^^^^^^^^^^^^^^^^
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1674, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1702, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1739, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1776, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 376, in handle_async_request
    with map_httpcore_exceptions():
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/.asdf/installs/python/3.12.6/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed
^C  Stopping...
(agent-service-toolkit)  ➜ agent-service-toolkit [git:main]✗ streamlit run src/streamlit_app.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.1.238:8501

2024-11-30 21:32:35.175 Uncaught app exception
Traceback (most recent call last):
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 377, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    with map_exceptions(exc_map):
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/.asdf/installs/python/3.12.6/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "/home/leo/Desktop/agent-service-toolkit/src/streamlit_app.py", line 340, in <module>
    asyncio.run(main())
  File "/home/leo/.asdf/installs/python/3.12.6/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/leo/.asdf/installs/python/3.12.6/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/.asdf/installs/python/3.12.6/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/leo/Desktop/agent-service-toolkit/src/streamlit_app.py", line 154, in main
    await draw_messages(stream, is_new=True)
  File "/home/leo/Desktop/agent-service-toolkit/src/streamlit_app.py", line 202, in draw_messages
    while msg := await anext(messages_agen, None):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/Desktop/agent-service-toolkit/src/client/client.py", line 192, in astream
    async with client.stream(
               ^^^^^^^^^^^^^^
  File "/home/leo/.asdf/installs/python/3.12.6/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1628, in stream
    response = await self.send(
               ^^^^^^^^^^^^^^^^
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1674, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1702, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1739, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1776, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 376, in handle_async_request
    with map_httpcore_exceptions():
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leo/.asdf/installs/python/3.12.6/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/leo/Desktop/agent-service-toolkit/.venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed
```

**Comment by JoshuaC215** [comment]
Sorry about that @leonardozilli ! Thanks for the detailed repro.

The issue was introduced in the recent update to how settings are managed. I think I fixed it so the relevant ENV settings will be properly synced from an `.env` file to both the service and streamlit app now which should resolve that. Let me know if it works how you expect on the latest main or if you still have problems with this.

**Comment by mjhof** [comment]
Hi @JoshuaC215, 
for me the same issue remains, also after pulling the latest update from main. Any ideas why this could occur?  

Thanks in advance :)

**Comment by JoshuaC215** [comment]
Hi @mjhof thanks for reporting.

I have been unable to repro this on my setup, or identify a possible issue. Can you share a little more details about:
- your OS / docker install
- Your .env file (no sensitive keys of course)
- exactly what commands you ran
- Error you saw

thank you!

**Comment by roopalav** [comment]
i just ran the repo in Linux Docker. 
In .env  file i added default model=gpt-4o-mini and openapikey, langsmithkey and tracing_v2=true. thats all.

**ConnectError: All connection attempts failed**
Traceback:
File "/usr/local/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
File "/usr/local/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
File "/app/streamlit_app.py", line 345, in <module>
    asyncio.run(main())
File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
File "/app/streamlit_app.py", line 159, in main
    await draw_messages(stream, is_new=True)
File "/app/streamlit_app.py", line 207, in draw_messages
    while msg := await anext(messages_agen, None):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/client/client.py", line 192, in astream
    async with client.stream(
File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1628, in stream
    response = await self.send(
               ^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1674, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1702, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1739, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1776, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 376, in handle_async_request
    with map_httpcore_exceptions():
File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc

**Comment by JoshuaC215** [comment]
@roopalav can you share the output logs from Docker for the service?
